### ISSUE TITLE
URL redirects dont work reliably

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1150]
For example:  https://syntax.fm/640

probably something to do with the slugification of the title. We should probably be storing the slug in the DB instead of generating it every time we need it

maybe related: https://github.com/syntaxfm/website/issues/1089

**Comment by wesbos** [comment]
@stolinski I think the slugification during import needs to match that of the old site. Seems characters such as `×` and `'` aren't URL friendly and don't match the current site.

related: https://github.com/syntaxfm/website/issues/1155

**Comment by wesbos** [comment]
http://localhost:5173/650 seems to break too:

TypeError: Cannot convert argument to a ByteString because the character at index 26 has a value of 8217 which is greater than 255.

**Comment by wesbos** [comment]
related to there being a `'` in the URL slug

**Comment by stolinski** [comment]
Should be fixed now with both slugification and adjustment to redirects here: 
c9de1a8

**Comment by wesbos** [comment]
@stolinski these URLs are still broken, both with different errors.

https://beta.syntax.fm/434
https://beta.syntax.fm/650

**Comment by stolinski** [comment]
Fixed in latest db sync.
